ignore:
    - "Scroller/EditableWrapper.js"
    - "TransferList"
coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        # advanced settings
        informational: false
        only_pulls: true
